# Generated by Django 6.0.6 on 2026-07-09 13:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', help_text='Stripe payment intent ID.', max_length=100)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Amount charged in USD.', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('item', models.CharField(help_text="What was purchased (e.g. 'Pro Plan').", max_length=100)),
                ('order_type', models.CharField(choices=[('purchase', 'Purchase'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade'), ('credit_pack', 'Credit Pack'), ('cancellation', 'Cancellation')], help_text='Type of order (purchase, renewal, upgrade, etc).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture.', null=True, upload_to='avatars/')),
                ('display_name', models.CharField(blank=True, help_text='Public display name (falls back to full_name or username).', max_length=100)),
                ('timezone', models.CharField(default='UTC', help_text="User timezone for display (e.g. 'Asia/Dubai').", max_length=50)),
                ('marketing_opt_in', models.BooleanField(default=False, help_text='Opted in to product updates and marketing emails.')),
                ('email_verified', models.BooleanField(default=False, help_text="Whether the user's email has been verified.")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('web', 'Web Browser'), ('ide', 'Cortex IDE'), ('cli', 'Cortex CLI'), ('jetbrains', 'JetBrains Plugin')], help_text='Which client created this session.', max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client.')),
                ('location', models.CharField(blank=True, default='', help_text="Geolocation string (e.g. 'Dubai, UAE').", max_length=200)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Full User-Agent string.')),
                ('is_current', models.BooleanField(default=False, help_text='True if this is the session the user is viewing from.')),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Active Session',
                'verbose_name_plural': 'Active Sessions',
                'ordering': ['-is_current', '-last_active'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable label (e.g. 'My IDE key').", max_length=100)),
                ('key_hash', models.CharField(help_text='SHA-256 hash of the raw API key.', max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text="First 8 chars of key for display (e.g. 'cx_live_abc').", max_length=12)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Permission scopes (e.g. ["chat", "models"]).')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
