# Generated by Django 6.0.6 on 2026-07-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='When the IDE last talked to the API.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_version',
            field=models.CharField(blank=True, db_index=True, default='', help_text="App version this user's IDE last reported.", max_length=20),
        ),
    ]
