"""
session_task.py
===============
Python conversion of two TypeScript source files from the original claude-code:

  src/tasks/stopTask.ts
      → StopTaskError, stop_session_task()

  src/tasks/LocalMainSessionTask.ts
      → SessionTaskState, SessionTaskRegistry, generate_session_task_id()

These types implement proper task-lifecycle management for the Cortex agent bridge.
The key insight from the TS source: a task is killed by cancelling its underlying
async primitive (TS: AbortController.abort(); Python: asyncio.Task.cancel()).

This replaces the previous ad-hoc `_stop_requested` flag-polling approach with
true asyncio task cancellation — CancelledError propagates through every `await`
in the call chain (_handle_chat → _call_llm → _execute_single_tool), guaranteeing
immediate interruption regardless of where the coroutine is paused.

Original TS reference:
    src/tasks/stopTask.ts       — StopTaskError class + stopTask() function
    src/tasks/LocalMainSessionTask.ts
        — generateMainSessionTaskId(), LocalMainSessionTaskState,
          registerMainSessionTask(), completeMainSessionTask()
"""

import asyncio
import logging
import secrets
import string
from dataclasses import dataclass, field
from typing import Any, Dict, Literal, Optional

log = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Constants / type aliases
# ─────────────────────────────────────────────────────────────────────────────

# Converted from LocalMainSessionTask.ts TASK_ID_ALPHABET
_TASK_ID_ALPHABET: str = string.digits + string.ascii_lowercase

TaskStatus = Literal["running", "completed", "failed", "stopped"]


# ─────────────────────────────────────────────────────────────────────────────
# Task ID generation
# ─────────────────────────────────────────────────────────────────────────────

def generate_session_task_id() -> str:
    """
    Generate a unique main-session task ID.

    Converted from LocalMainSessionTask.ts generateMainSessionTaskId():
        Uses 's' prefix (main-session) vs 'a' prefix (agent sub-tasks).
        8 random alphanumeric characters → ~36^8 ≈ 2.8 trillion combinations.
    """
    return "s" + "".join(secrets.choice(_TASK_ID_ALPHABET) for _ in range(8))


# ─────────────────────────────────────────────────────────────────────────────
# StopTaskError
# ─────────────────────────────────────────────────────────────────────────────

class StopTaskError(Exception):
    """
    Raised when a task cannot be stopped.

    Converted from stopTask.ts StopTaskError class.
    Callers inspect `error.code` to distinguish the failure reason.
    """

    def __init__(
        self,
        message: str,
        code: Literal["not_found", "not_running", "unsupported_type"],
    ) -> None:
        super().__init__(message)
        self.code = code


# ─────────────────────────────────────────────────────────────────────────────
# SessionTaskState
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class SessionTaskState:
    """
    State for one AI session task running inside Cortex.

    Simplified Python conversion of LocalMainSessionTask.ts
    LocalMainSessionTaskState (which extends LocalAgentTaskState).

    Fields
    ------
    task_id         Unique ID generated by generate_session_task_id().
    description     Short description of the user prompt (first 100 chars).
    status          Lifecycle status: running → completed | failed | stopped.
    asyncio_task    The asyncio.Task wrapping AgentWorker._handle_chat().
                    Set by the worker after asyncio.create_task().
                    Cancelling this is the Python equivalent of TS kill() /
                    AbortController.abort().
    abort_controller  Real AbortController from utils/abortController.py.
                    Signals tool-level cancellation (GrepTool ripgrep, etc.)
                    separately from the asyncio task cancellation.
    notified        True once a completion/stop event has been emitted.
    """

    task_id: str
    description: str
    status: TaskStatus = "running"
    asyncio_task: Optional[asyncio.Task] = field(default=None, repr=False)
    abort_controller: Optional[Any] = field(default=None, repr=False)
    notified: bool = False


# ─────────────────────────────────────────────────────────────────────────────
# SessionTaskRegistry
# ─────────────────────────────────────────────────────────────────────────────

class SessionTaskRegistry:
    """
    Registry of running AI session tasks.

    Simplified Python conversion of AppStateStore.ts AppState.tasks map.
    Cortex runs a single main-session task at a time; this class tracks the
    active task and exposes the same task-lifecycle interface used by
    stop_session_task().
    """

    def __init__(self) -> None:
        self._tasks: Dict[str, SessionTaskState] = {}
        self._active_task_id: Optional[str] = None

    # ── Registration ───────────────────────────────────────────

    def register(self, state: SessionTaskState) -> None:
        """
        Register a new task as the active session task.

        Equivalent to registerTask(taskState, setAppState) in
        LocalMainSessionTask.ts registerMainSessionTask().
        """
        self._tasks[state.task_id] = state
        self._active_task_id = state.task_id
        log.info(
            f"[TASK_REGISTRY] Registered task {state.task_id!r}: "
            f"{state.description[:60]}"
        )

    # ── Lookup ─────────────────────────────────────────────────

    def get(self, task_id: str) -> Optional[SessionTaskState]:
        """Return task by ID, or None if not found."""
        return self._tasks.get(task_id)

    def get_active(self) -> Optional[SessionTaskState]:
        """Return the most recently registered (active) task, or None."""
        if self._active_task_id:
            return self._tasks.get(self._active_task_id)
        return None

    # ── Status update ──────────────────────────────────────────

    def update_status(self, task_id: str, status: TaskStatus) -> None:
        """Update task status (running → completed/failed/stopped)."""
        task = self._tasks.get(task_id)
        if task:
            task.status = status
            log.info(f"[TASK_REGISTRY] Task {task_id!r} → status={status!r}")

    # ── Removal ────────────────────────────────────────────────

    def remove(self, task_id: str) -> None:
        """Remove a completed/stopped task from the registry."""
        self._tasks.pop(task_id, None)
        if self._active_task_id == task_id:
            self._active_task_id = None
        log.debug(f"[TASK_REGISTRY] Removed task {task_id!r}")


# ─────────────────────────────────────────────────────────────────────────────
# stop_session_task
# ─────────────────────────────────────────────────────────────────────────────

def stop_session_task(
    task_id: str,
    registry: SessionTaskRegistry,
) -> Dict[str, str]:
    """
    Look up a task by ID, validate it is running, cancel its asyncio.Task,
    and mark it as stopped.

    Python conversion of stopTask.ts stopTask():

        TS pattern:
            await taskImpl.kill(taskId, setAppState)
            → internally calls abortController.abort()

        Python equivalent:
            asyncio_task.cancel()       — injects CancelledError at next await
            abort_controller.abort()    — terminates tool subprocesses (GrepTool)

    Parameters
    ----------
    task_id   ID of the task to stop.
    registry  SessionTaskRegistry instance.

    Returns
    -------
    dict with task_id and description on success.

    Raises
    ------
    StopTaskError  if task not found or not running.
    """
    task = registry.get(task_id)

    if not task:
        raise StopTaskError(
            f"No task found with ID: {task_id!r}",
            "not_found",
        )

    if task.status != "running":
        raise StopTaskError(
            f"Task {task_id!r} is not running (status={task.status!r})",
            "not_running",
        )

    # ── 1. Cancel the asyncio.Task ───────────────────────────────────────────
    # asyncio.Task.cancel() is thread-safe — it schedules a CancelledError to
    # be injected at the next `await` inside _handle_chat → _call_llm →
    # _execute_single_tool, regardless of which await is currently suspended.
    if task.asyncio_task is not None and not task.asyncio_task.done():
        task.asyncio_task.cancel()
        log.info(f"[TASK_REGISTRY] asyncio.Task.cancel() → {task_id!r}")
    else:
        log.info(
            f"[TASK_REGISTRY] No live asyncio.Task for {task_id!r} "
            "(may not have started yet — stop flag will catch it)"
        )

    # ── 2. Abort tool-level work via AbortController ─────────────────────────
    # GrepTool extracts `signal = getattr(abort_controller, "signal", None)`
    # and passes it to ripgrep(). Calling abort() terminates the subprocess.
    if task.abort_controller is not None:
        try:
            task.abort_controller.abort("interrupt")
            log.info(
                f"[TASK_REGISTRY] AbortController.abort('interrupt') → {task_id!r}"
            )
        except Exception as exc:
            log.warning(
                f"[TASK_REGISTRY] AbortController.abort() failed for "
                f"{task_id!r}: {exc}"
            )

    # ── 3. Mark task as stopped ──────────────────────────────────────────────
    registry.update_status(task_id, "stopped")

    return {"task_id": task_id, "description": task.description}


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

__all__ = [
    "StopTaskError",
    "TaskStatus",
    "SessionTaskState",
    "SessionTaskRegistry",
    "generate_session_task_id",
    "stop_session_task",
]
