# Generated by Django 6.0.6 on 2026-07-09 13:03

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(db_index=True, help_text='SHA-256 hash of hardware ID (never store raw device IDs).', max_length=64)),
                ('ide_version', models.CharField(help_text="IDE version that crashed (e.g. '0.9.2').", max_length=20)),
                ('os_version', models.CharField(help_text="OS version (e.g. 'Windows 11 23H2').", max_length=100)),
                ('error_type', models.CharField(db_index=True, help_text="Error classification (e.g. 'QtWebEngine_AccessViolation').", max_length=200)),
                ('error_message', models.TextField(help_text='Human-readable error message.')),
                ('stack_trace', models.TextField(blank=True, default='', help_text='Stack trace if available. May contain user code — treat as sensitive.')),
                ('context', models.CharField(blank=True, default='', help_text='What the user was doing when the crash occurred.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Crash Report',
                'verbose_name_plural': 'Crash Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Config version (e.g. '2026.06.1'). IDE compares to local cache.", max_length=50, unique=True)),
                ('config_json', models.JSONField(help_text='Full model config JSON — providers, models, defaults, failover order.')),
                ('min_ide_version', models.CharField(default='0.9.0', help_text='Minimum IDE version required to use this config.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only the active config is served to IDEs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Model Configuration',
                'verbose_name_plural': 'Model Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=20, unique=True)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('force_update', models.BooleanField(default=False, help_text='If checked, desktop IDE will BLOCK usage until this version is installed.')),
                ('file', models.FileField(max_length=255, upload_to=api.models._release_upload_path)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('sha256', models.CharField(default='', help_text='SHA-256 checksum', max_length=64)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Only active releases are served')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('refresh_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('pro', 'Pro'), ('pro_yearly', 'Pro (Yearly)')], help_text='Which plan was purchased.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount charged.', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='USD or INR.', max_length=3)),
                ('gateway', models.CharField(choices=[('paypal', 'PayPal'), ('razorpay', 'Razorpay')], help_text='Which payment gateway processed this.', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('paypal_order_id', models.CharField(blank=True, default='', help_text='PayPal v2 order ID (created client-side by JS SDK).', max_length=100)),
                ('paypal_capture_id', models.CharField(blank=True, default='', help_text='Capture ID after successful PayPal capture.', max_length=100)),
                ('paypal_payer_id', models.CharField(blank=True, default='', help_text='PayPal payer ID.', max_length=100)),
                ('paypal_payer_email', models.CharField(blank=True, default='', help_text='PayPal payer email.', max_length=200)),
                ('razorpay_order_id', models.CharField(blank=True, default='', help_text='Razorpay order ID (created server-side).', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', help_text='Razorpay payment ID after success.', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, default='', help_text='HMAC signature for Razorpay verification.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(db_index=True, help_text='Unique license key the IDE uses to validate subscription.', max_length=64, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Subscriber email (used for magic link sign-in).', max_length=254)),
                ('plan', models.CharField(choices=[('pro', 'Pro'), ('pro_yearly', 'Pro (Yearly)')], db_index=True, default='pro', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, default='', help_text='Stripe customer ID (if using Stripe billing).', max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', help_text='Stripe subscription ID (if using Stripe billing).', max_length=100)),
                ('paypal_order_id', models.CharField(blank=True, default='', help_text='Last PayPal order ID that activated this subscription.', max_length=100)),
                ('razorpay_order_id', models.CharField(blank=True, default='', help_text='Last Razorpay order ID that activated this subscription.', max_length=100)),
                ('current_period_start', models.DateTimeField(help_text='Start of current billing period.')),
                ('current_period_end', models.DateTimeField(help_text='End of current billing period (credits reset after this).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(choices=[('deepseek-v4-pro-promo', 'DeepSeek V4 Pro (Promo)'), ('deepseek-v4-pro-base', 'DeepSeek V4 Pro (Base)'), ('mimo-v2.5-pro', 'MiMo V2.5 Pro'), ('mimo-v2.5', 'MiMo V2.5'), ('mistral-large-latest', 'Mistral Large'), ('other', 'Other')], help_text='Which included model was used.', max_length=50)),
                ('input_cache_hit', models.PositiveIntegerField(default=0, help_text='Input tokens served from prompt cache.')),
                ('input_cache_miss', models.PositiveIntegerField(default=0, help_text='Input tokens NOT from prompt cache.')),
                ('output_tokens', models.PositiveIntegerField(default=0, help_text='Output tokens generated.')),
                ('ocr_pages', models.PositiveIntegerField(default=0, help_text='Number of images/pages processed via Mistral OCR.')),
                ('input_tokens', models.PositiveIntegerField(default=0, help_text='Total input tokens (cache_hit + cache_miss). Auto-populated.')),
                ('raw_cost_usd', models.DecimalField(decimal_places=8, default=0, help_text='Raw infrastructure cost in USD before markup.', max_digits=12)),
                ('gross_cost_usd', models.DecimalField(decimal_places=8, default=0, help_text='Cost in USD after 20% platform markup.', max_digits=12)),
                ('credits_consumed', models.PositiveIntegerField(default=0, help_text='Wallet credit points deducted (= gross_cost_usd / $0.01).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api.subscription')),
            ],
            options={
                'verbose_name': 'Usage Log',
                'verbose_name_plural': 'Usage Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
