"""Persistent PowerShell sessions shared by the AI and the Terminal panel.

The AI's Bash tool used to start a fresh `powershell -NonInteractive -Command`
for every call, with no stdin. Nothing carried over between calls (`cd`,
variables, `$env:` changes, an activated venv), and anything that asked for
input (ssh, a y/n question, a password) hung until the timeout. Now the AI
types into a real ConPTY shell that is shown as a "Cortex AI" terminal tab,
where the user can watch and type too.

How the end of a command and its exit code are known: the shell starts with a
small integration script (the same approach as terminal shell integration, OSC 633):

    ESC ] 633 ; C BEL             command accepted, its output starts
    ESC ] 633 ; D ; <code> BEL    command finished (written by the prompt)
    ESC ] 633 ; P ; Cwd=<dir> BEL current directory (written by the prompt)

xterm.js ignores these sequences; this module parses them.

Handing over to the user: while an AI command runs, a quiet last line that
looks like a prompt (password, yes/no, "press any key", ...) raises
`on_input_needed`. For a password or a question the command's clock stops
until the user answers, and the AI cannot type into the session.

Background commands (servers, watchers): `run(background=True)` returns after
a short startup window and leaves the command running in its tab; the next AI
command gets another session. `read_background` / `kill_background` follow it.

SSH: `ssh user@host` with no remote command leaves the session inside a remote
shell ("remote mode"). The markers above do not exist there, so each command is
followed by `printf` of a one-time token plus `$?`, and its end is that token.
While a session is remote, AI commands always go to it, never to this machine.

Keystrokes typed into the tab go straight to the PTY. They are never logged,
stored, or added to the AI's output, and a password prompt does not echo, so
the captured output never contains the password.
"""
import base64
import itertools
import os
import re
import shlex
import sys
import threading
import time
from typing import Callable, List, NamedTuple, Optional, Tuple

from src.utils.logger import get_logger

log = get_logger("terminal_session")

try:
    import winpty
    _WINPTY = True
except Exception:  # not Windows, or pywinpty missing
    winpty = None
    _WINPTY = False

_SHELL_DIR = os.path.join(os.path.expanduser("~"), ".cortex", "shell")

# Loaded with `-NoExit -Command . '<file>'` after the user's profile.
# Ctrl+C: pywinpty spawns the shell with CREATE_NEW_PROCESS_GROUP, which
# disables Ctrl+C for it and its children; SetConsoleCtrlHandler(NULL, FALSE)
# re-enables it (same fix as xterm_terminal._PS_ENABLE_CTRL_C).
# Exit code: $? says whether the last command failed. $LASTEXITCODE is only
# trusted when THIS command changed it, otherwise a failed cmdlet after an
# earlier `exit 3` would report 3.
_INTEGRATION_PS1 = r'''# Cortex shell integration, generated by src/core/terminal_session.py
$md='[DllImport("kernel32.dll")] public static extern bool SetConsoleCtrlHandler(IntPtr h, bool add);'
try {
  $null=Add-Type -Namespace CortexNative -Name K32 -PassThru -MemberDefinition $md
  $null=[CortexNative.K32]::SetConsoleCtrlHandler([IntPtr]::Zero,$false)
} catch {}
Import-Module PSReadLine -ErrorAction SilentlyContinue
$global:__cxE = [char]27; $global:__cxB = [char]7; $global:__cxLec = $global:LASTEXITCODE
if (Test-Path function:PSConsoleHostReadLine) {
  $global:__cxOrigReadLine = $function:PSConsoleHostReadLine
  function global:PSConsoleHostReadLine {
    $line = & $global:__cxOrigReadLine
    $global:__cxLec = $global:LASTEXITCODE
    [Console]::Write("$($global:__cxE)]633;C$($global:__cxB)")
    $line
  }
}
$global:__cxOrigPrompt = $function:prompt
function global:prompt {
  $ok = $global:?; $code = $global:LASTEXITCODE
  $ec = if ($ok) { 0 } elseif ($code -and $code -ne $global:__cxLec) { $code } else { 1 }
  $cwd = (Get-Location).ProviderPath
  [Console]::Write("$($global:__cxE)]633;D;$ec$($global:__cxB)$($global:__cxE)]633;P;Cwd=$cwd$($global:__cxB)")
  & $global:__cxOrigPrompt
}
'''

_MARK_RE = re.compile(r"\x1b\]633;(?:(C)|D;(-?\d+)|P;Cwd=([^\x07]*))\x07")
_MARK_INTRO = "\x1b]633;"
_OSC_RE = re.compile(r"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)")
_CSI_RE = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")
_ESC_RE = re.compile(r"\x1b[@-Z\\-_]")
_CTRL_RE = re.compile(r"[\x00-\x08\x0b-\x1f\x7f]")

# Prompt shapes, matched against the last line of a command that went quiet.
# "secret" and "confirm" pause the command's clock; "input" is only a guess
# (a line ending in ':' '?' '>'), so it pauses nothing and clears on output.
_SECRET_RE = re.compile(
    r"(pass(word|phrase|code)|\bpin\b|\btoken\b|secret|verification code|security code"
    r"|one[- ]time|\botp\b|\b2fa\b|authenticat\w* code)[^\n]{0,120}[:：]\s*$", re.I)
_CONFIRM_RE = re.compile(
    r"(\((yes/no|y/n)[^)\n]*\)|\[(y/n|yes/no)\]|\(default is \"?\w+\"?\))\s*[?:]?\s*$"
    r"|\b(continue|proceed|overwrite|replace|are you sure|do you want)\b[^\n]{0,160}\?\s*$"
    r"|press (any key|enter)\b[^\n]{0,80}$", re.I)
_INPUT_RE = re.compile(r"\S[^\n]{0,160}[:?>]\s*$")
# Sign-in prompts: git's "Username for 'https://github.com':", PuTTY's "login as:".
_LOGIN_RE = re.compile(r"\b(user ?name|login|e-?mail|account)\b[^\n]{0,120}[:：]\s*$", re.I)
# Prompt kinds that stop the command's clock until the user answers.
# "gcm": git over HTTPS signs in through Git Credential Manager's own window,
# which prints nothing to the terminal; it is found as a child process.
_PAUSING = ("secret", "confirm", "login", "gcm")
_GCM_QUIET = 1.5           # s of silence before looking for a sign-in window
_GCM_PROMPT = "Git Credential Manager sign-in window"
# A POSIX shell prompt: "user@host:~$ ", "root@box:/# ", "host% ", "> ".
_SHELL_PROMPT_RE = re.compile(r"[$#%>]\s*$")
# Back at the local PowerShell prompt, or ssh's own goodbye: the SSH session ended.
_LOCAL_PROMPT_RE = re.compile(r"^PS [^\n>]*>\s*$")
_SSH_CLOSED_RE = re.compile(r"Connection to \S+ closed", re.I)

_REMOTE_FMT = "__CX_%s_%s__"       # printf format typed after a remote command
_SSH_OPTS_WITH_ARG = set("BbcDEeFIiJLlmOopQRSWw")

_PROMPT_QUIET = 0.5        # s of silence before a prompt-shaped line counts
_INPUT_QUIET = 4.0         # the generic guess needs a longer silence
_SSH_READY_QUIET = 0.8     # s of silence on a shell prompt = remote shell ready
_REPLAY_MAX = 256 * 1024   # raw output kept so a tab opened later shows history
_OUTPUT_MAX = 200 * 1024   # cleaned output handed to the AI (the tail is kept)
_TAIL_MAX = 4096           # raw tail kept for prompt detection
_MIN_COLS = 60             # a hidden tab reports tiny sizes; never shrink below this
_READY_TIMEOUT = 30.0      # first prompt (profile + integration) took 3.7s here
_MAX_AI_SESSIONS = 4

ANSWERED_NOTE = "[The user answered a prompt in the terminal. Their input is not shown.]"


class RunResult(NamedTuple):
    code: Optional[int]          # None while still running
    output: str
    timed_out: bool
    running: bool = False        # left running in the background
    busy: bool = False           # the remote shell is busy, nothing was run
    shell_id: int = 0
    remote: Optional[str] = None  # user@host when it ran over SSH
    note: str = ""


def clean_output(raw: str) -> str:
    """Terminal output as plain text: escapes removed, \\r overwrites applied."""
    s = _OSC_RE.sub("", raw)
    s = _CSI_RE.sub("", s)
    s = _ESC_RE.sub("", s)
    s = s.replace("\r\n", "\n")
    lines = []
    for line in s.split("\n"):
        if "\r" in line:  # progress redraws: the last non-empty write wins
            line = next((p for p in reversed(line.split("\r")) if p), "")
        lines.append(_CTRL_RE.sub("", line).rstrip())
    return "\n".join(lines).strip("\n")


def classify_prompt(line: str, quiet: float) -> Optional[str]:
    """'secret', 'confirm', 'input' or None for a command's quiet last line."""
    line = (line or "").strip()
    if not line:
        return None
    if _SECRET_RE.search(line):
        return "secret"
    if _LOGIN_RE.search(line):
        return "login"
    if _CONFIRM_RE.search(line):
        return "confirm"
    if quiet >= _INPUT_QUIET and _INPUT_RE.search(line):
        return "input"
    return None


def ssh_destination(command: str) -> Optional[str]:
    """user@host when `command` opens an interactive ssh shell, else None
    (a remote command, -N or -f means it is not an interactive shell)."""
    try:
        toks = shlex.split((command or "").strip(), posix=True)
    except ValueError:
        return None
    if not toks:
        return None
    exe = toks[0].replace("\\", "/").rsplit("/", 1)[-1].lower()
    if exe not in ("ssh", "ssh.exe"):
        return None
    i, dest, login = 1, None, None
    while i < len(toks):
        t = toks[i]
        if t == "--":
            i += 1
            if i < len(toks):
                dest = toks[i]
                i += 1
            break
        if t.startswith("-") and len(t) > 1:
            flags = t[1:]
            for j, f in enumerate(flags):
                if f in "Nf":
                    return None
                if f in _SSH_OPTS_WITH_ARG:
                    arg = flags[j + 1:]
                    if not arg:
                        i += 1
                        arg = toks[i] if i < len(toks) else ""
                    if f == "l":
                        login = arg
                    break
            i += 1
            continue
        dest = t
        i += 1
        break
    if not dest or i < len(toks):
        return None
    if login and "@" not in dest:
        dest = f"{login}@{dest}"
    return dest


def command_lines(code: str) -> List[str]:
    """Lines of a code block to type into a terminal: blank lines dropped, and
    a leading "$ " / "PS C:\\> " / "> " prompt removed when every line has one."""
    lines = [ln.rstrip() for ln in (code or "").strip("\n").splitlines()]
    body = [ln for ln in lines if ln.strip()]
    pr = re.compile(r"^\s*(\$|PS [^>]*>|>)\s")
    if body and all(pr.match(ln) for ln in body):
        lines = [pr.sub("", ln) for ln in lines]
    return [ln for ln in lines if ln.strip()]


_SUDO_RE = re.compile(r"(^|[\s;&|(`$])sudo\b")


def _remote_line(command: str, nonce: str, sudo_reprompt: bool = True) -> str:
    """The line typed into a remote POSIX shell: the command, then a token
    with its exit code. The token is assembled by printf, so the echo of the
    typed line never contains it.

    sudo remembers a password for ~15 minutes. With `sudo_reprompt`, a
    command that uses sudo first drops that memory (`sudo -k`), so sudo asks
    the user again: the AI can never ride on a password typed earlier."""
    cmd = command.strip().rstrip(";").rstrip()
    tail = f"; printf '\\n{_REMOTE_FMT}\\n' D{nonce} \"$?\""
    if (not cmd or "\n" in cmd or "\r" in cmd or "\t" in cmd or "#" in cmd
            or cmd.endswith(("&", "|", "\\")) or len(cmd) > 1500):
        b64 = base64.b64encode(command.encode("utf-8")).decode("ascii")
        cmd = f"eval \"$(printf %s '{b64}' | base64 -d)\""
    if sudo_reprompt and _SUDO_RE.search(command):
        cmd = "sudo -k 2>/dev/null; " + cmd
    return cmd + tail


def _setting(key: str, default):
    try:
        from src.config.settings import get_settings
        return get_settings().get("terminal", key, default=default)
    except Exception:
        return default


def _strip_remote(raw: str, rx: "re.Pattern") -> str:
    """Remote output: cut at the token, drop the echoed command line."""
    m = rx.search(raw)
    text = clean_output(raw[:m.start()] if m else raw)
    k = text.find(_REMOTE_FMT)
    if k != -1:
        nl = text.find("\n", k)
        text = text[nl + 1:] if nl != -1 else ""
    return text.strip("\n")


class TerminalSession:
    """A persistent PowerShell in a ConPTY, with command boundaries."""

    _ids = itertools.count(1)

    def __init__(self, cwd: str, env: Optional[dict] = None, name: str = "Cortex AI",
                 cols: int = 200, rows: int = 40):
        self.id = next(self._ids)
        self.name = name
        self.root = os.path.normcase(os.path.abspath(cwd)) if cwd else ""
        self.cwd = cwd or os.path.expanduser("~")
        self._env = env
        self._size = (cols, rows)
        self.pty = None
        self._cond = threading.Condition(threading.RLock())
        self._write_lock = threading.Lock()
        self._run_lock = threading.Lock()
        self._subscribers: List[Callable[[str], None]] = []
        self._replay = ""
        self._scan = ""              # held-back tail that may be a split marker
        self._alive = False
        self._ready = False          # first prompt seen
        self._busy = False           # between C and D
        self._user_dirty = False     # user has typed part of a line at the prompt
        self._last_activity = time.monotonic()   # output or user typing
        self._last_output = time.monotonic()     # output only
        # capture state for the AI command in flight
        self._cap_active = False
        self._cap_started = False    # saw C (or remote mode)
        self._cap_pre: List[str] = []
        self._cap_buf: List[str] = []
        self._cap_len = 0
        self._cap_tail = ""
        self._cap_done = False
        self._cap_code: Optional[int] = None
        # handover state
        self._awaiting: Optional[Tuple[str, str]] = None   # (kind, prompt line)
        self._awaiting_since = 0.0
        self._answered_at: Optional[float] = None
        self._gcm_checked = 0.0      # last look for a Git Credential Manager window
        # background command left running (output keeps being captured)
        self._bg: Optional[dict] = None
        self._bg_final: Optional[RunResult] = None
        # SSH remote mode
        self.remote: Optional[str] = None
        self.adopted = False         # a user's own tab lent to the AI (see adopt)
        self._remote_re: Optional["re.Pattern"] = None
        self._remote_dropped = False
        # set by the manager: UI callbacks (called on a worker/reader thread)
        self.on_input_needed: Optional[Callable[[str, str], None]] = None
        self.on_input_done: Optional[Callable[[str], None]] = None
        self.on_remote_changed: Optional[Callable[[str], None]] = None

    # ── the user's own terminal, lent to the AI ──────────────────────
    @classmethod
    def adopt(cls, pty, name: str, remote: str, history: str = "") -> "TerminalSession":
        """Wrap a user's terminal tab that is logged into a server over SSH,
        after the user allowed Cortex AI to use it. The tab keeps its pty and
        reader and hands output over through feed(); close() only lets go."""
        s = cls("", None, name=name)
        s.pty = pty
        s.adopted = True
        s._alive = s._ready = s._busy = True
        s.remote = remote
        s._replay = (history or "")[-_REPLAY_MAX:]
        log.info("[AI-TERM] session %d: the user gave AI access to their SSH session (%s)",
                 s.id, name)
        return s

    def feed(self, data: str):
        """Output of an adopted tab (its own reader calls this)."""
        if self.adopted and self._alive and data:
            self._dispatch(data)

    def note_user_input(self, data: str):
        """Keys the user typed into an adopted tab (the tab writes them
        itself). Tracked for activity and answers only; never logged or kept."""
        with self._cond:
            self._note_user_locked(data)

    def _note_user_locked(self, data: str):
        now = time.monotonic()
        self._last_activity = now
        if "\r" in data or "\n" in data:
            self._user_dirty = False
            if self._awaiting is not None:
                self._answered_at = now
            self._cond.notify_all()
        elif data != "\x03":
            self._user_dirty = True

    def set_remote(self, host: Optional[str]):
        """The user allowed (host) or stopped (None) AI use of an SSH session
        they opened in this session's own tab."""
        with self._cond:
            self.remote = host or None
        _safe(self.on_remote_changed, host or "")

    def _end_remote(self):
        """The SSH session ended. Caller holds the lock."""
        host, self.remote = self.remote, None
        self._remote_dropped = True
        if self.adopted:
            self._alive = False  # the AI's access to the user's tab ends with it
        log.info("[AI-TERM] session %d: SSH session ended", self.id)
        _safe(self.on_remote_changed, "")

    # ── lifecycle ─────────────────────────────────────────────────────
    def start(self) -> bool:
        if sys.platform != "win32" or not _WINPTY:
            return False
        try:
            os.makedirs(_SHELL_DIR, exist_ok=True)
            path = os.path.join(_SHELL_DIR, "cortex_integration.ps1")
            try:
                with open(path, encoding="utf-8-sig") as f:
                    current = f.read()
            except OSError:
                current = None
            if current != _INTEGRATION_PS1:
                with open(path, "w", encoding="utf-8-sig") as f:
                    f.write(_INTEGRATION_PS1)
            # Single quotes only: a double-quoted -Command argument reaches
            # PowerShell with the quotes and runs nothing (see xterm_terminal).
            cmd = ("powershell.exe -NoLogo -ExecutionPolicy Bypass -NoExit -Command . '"
                   + path.replace("'", "''") + "'")
            env = dict(self._env if self._env is not None else os.environ)
            env["TERM"] = "xterm-256color"
            env["COLORTERM"] = "truecolor"
            cols, rows = self._size
            self.pty = winpty.PtyProcess.spawn(cmd, cwd=self.cwd, env=env, dimensions=(rows, cols))
        except Exception as e:
            log.warning("[AI-TERM] could not start the shared session: %s", e)
            self.pty = None
            return False
        self._alive = True
        threading.Thread(target=self._reader, daemon=True,
                         name=f"cortex-ai-term-{self.id}").start()
        log.info("[AI-TERM] session %d started, pid=%s, cwd=%s", self.id, self.pid, self.cwd)
        return True

    @property
    def pid(self) -> Optional[int]:
        try:
            return int(self.pty.pid) if self.pty else None
        except Exception:
            return None

    @property
    def is_alive(self) -> bool:
        try:
            return self._alive and bool(self.pty) and self.pty.isalive()
        except Exception:
            return False

    @property
    def awaiting(self) -> Optional[Tuple[str, str]]:
        """(kind, prompt) while a command waits on the user, else None."""
        return self._awaiting

    @property
    def background_running(self) -> bool:
        return self._bg is not None and not self._cap_done and self._alive

    @property
    def usable(self) -> bool:
        """Free for an AI command: at the local prompt, nothing half-typed."""
        return (self.is_alive and not self.remote and not self._busy
                and not self._user_dirty and not self.background_running)

    def close(self):
        with self._cond:
            self._alive = False
            if self.adopted:
                self.remote = None
            self._cond.notify_all()
        if self.adopted:
            # The tab owns this shell: stop the AI's access, never close it.
            log.info("[AI-TERM] session %d: AI access to the user's terminal released", self.id)
            return
        pty, self.pty = self.pty, None
        if pty is not None:
            try:
                pty.terminate(force=True)
            except Exception:
                pass
            log.info("[AI-TERM] session %d closed", self.id)

    # ── output ────────────────────────────────────────────────────────
    def _reader(self):
        pty = self.pty
        while pty is not None:
            try:
                data = pty.read(65536)
            except EOFError:
                break
            except Exception:
                try:
                    if not pty.isalive():
                        break
                except Exception:
                    break
                time.sleep(0.01)
                continue
            if not data:
                try:
                    if not pty.isalive():
                        break
                except Exception:
                    break
                time.sleep(0.005)
                continue
            self._dispatch(data)
        with self._cond:
            self._alive = False
            self._cond.notify_all()
        self._dispatch("\r\n\x1b[90m[ Cortex AI session ended ]\x1b[0m\r\n")

    def _dispatch(self, data: str):
        with self._cond:
            self._feed(data)
            self._replay = (self._replay + data)[-_REPLAY_MAX:]
            self._last_activity = self._last_output = time.monotonic()
            if self.remote and self.adopted:
                # A user's own tab has no shell markers: the SSH session is
                # over when ssh says so or the local PowerShell prompt is back.
                last = clean_output(self._replay[-600:]).rsplit("\n", 1)[-1].strip()
                if _LOCAL_PROMPT_RE.match(last) or _SSH_CLOSED_RE.search(clean_output(data)):
                    self._end_remote()
            subs = list(self._subscribers)
            self._cond.notify_all()
        for cb in subs:
            try:
                cb(data)
            except Exception:
                pass

    def _feed(self, data: str):
        """Split output into text and markers. Caller holds the lock."""
        buf = self._scan + data
        pos = 0
        for m in _MARK_RE.finditer(buf):
            self._text(buf[pos:m.start()])
            if m.group(1):
                self._busy = True
                if self._cap_active:
                    self._cap_started = True
            elif m.group(2) is not None:
                self._busy = False
                self._user_dirty = False
                self._ready = True
                if self.remote:
                    self._end_remote()  # the local prompt is back
                if self._cap_active and not self._cap_done:
                    self._cap_done = True
                    self._cap_code = int(m.group(2))
            else:
                self.cwd = m.group(3)
            pos = m.end()
        rest = buf[pos:]
        # Hold back a tail that may be the first half of one of OUR markers
        # split across two reads, and nothing else. Holding back any trailing
        # escape swallowed real text: bash writes ESC[?2004h right before its
        # prompt, so "ESC[?2004hfake@host:~$ " sat unseen and neither the SSH
        # prompt nor a coloured "ESC[32mPassword: " prompt was ever detected.
        k = rest.rfind("\x1b")
        tail = rest[k:] if k != -1 else ""
        if (tail and len(tail) < 1024 and "\x07" not in tail
                and (_MARK_INTRO.startswith(tail) or tail.startswith(_MARK_INTRO))):
            self._text(rest[:k])
            self._scan = tail
        else:
            self._text(rest)
            self._scan = ""

    def _text(self, t: str):
        if not t or not self._cap_active or self._cap_done:
            return
        if self._cap_started:
            self._cap_buf.append(t)
            self._cap_len += len(t)
            self._cap_tail = (self._cap_tail + t)[-_TAIL_MAX:]
            if self._cap_len > 4 * _OUTPUT_MAX:  # bound memory on floods
                joined = "".join(self._cap_buf)[-2 * _OUTPUT_MAX:]
                self._cap_buf, self._cap_len = [joined], len(joined)
                if self._bg is not None:
                    self._bg["read"] = 0
            if self._remote_re is not None:
                m = self._remote_re.search(self._cap_tail)
                if m:
                    self._cap_done = True
                    self._cap_code = int(m.group(1))
        else:
            self._cap_pre.append(t)

    def subscribe(self, cb: Callable[[str], None]) -> str:
        """Add an output listener; returns the output so far to replay."""
        with self._cond:
            self._subscribers.append(cb)
            return self._replay

    def unsubscribe(self, cb):
        with self._cond:
            try:
                self._subscribers.remove(cb)
            except ValueError:
                pass

    # ── input ─────────────────────────────────────────────────────────
    def write(self, data: str, user: bool = False) -> bool:
        """Write to the shell. `user` input is never logged or captured.

        While a command waits for a password, only the user may type: the AI
        side can send Ctrl+C (Stop, timeout) and nothing else.
        """
        if not data or self.pty is None:
            return False
        with self._cond:
            if user:
                # Typing (a password, a y/n answer) counts as activity, so an
                # AI command waiting on the user is not timed out meanwhile.
                self._note_user_locked(data)
            elif (self._awaiting is not None and self._awaiting[0] == "secret"
                  and data != "\x03"):
                log.warning("[AI-TERM] blocked AI input while a password prompt is open")
                return False
        with self._write_lock:
            try:
                self.pty.write(data)
            except Exception as e:
                log.warning("[AI-TERM] write failed: %s", type(e).__name__)
                return False
        return True

    def resize(self, cols: int, rows: int):
        if cols < _MIN_COLS or rows < 5 or self.pty is None:
            return
        self._size = (cols, rows)
        try:
            self.pty.setwinsize(rows, cols)
        except Exception:
            pass

    def _gcm_running(self) -> bool:
        """Is Git Credential Manager (git's HTTPS sign-in window) running
        under this shell? Current and older builds: git-credential-manager*."""
        pid = self.pid
        if not pid or self.adopted:
            return False
        try:
            import psutil
            for c in psutil.Process(pid).children(recursive=True):
                try:
                    if c.name().lower().startswith("git-credential-manager"):
                        return True
                except Exception:
                    continue
        except Exception:
            return False
        return False

    def interrupt(self):
        """Ctrl+C, then stop anything the shell started (the shell survives).
        Over SSH only Ctrl+C is sent: the local child is ssh.exe itself."""
        self.write("\x03")
        pid = self.pid
        if not pid or self.remote:
            return
        try:
            import psutil
            kids = psutil.Process(pid).children(recursive=True)
        except Exception:
            return
        for c in kids:
            try:
                c.terminate()
            except Exception:
                pass
        try:
            _gone, alive = psutil.wait_procs(kids, timeout=2)
            for c in alive:
                try:
                    c.kill()
                except Exception:
                    pass
        except Exception:
            pass

    # ── handover ──────────────────────────────────────────────────────
    def _set_awaiting(self, kind: str, prompt: str, on_wait):
        """Caller holds the lock."""
        self._awaiting = (kind, prompt)
        self._awaiting_since = time.monotonic()
        self._answered_at = None
        log.info("[AI-TERM] session %d: command is waiting for user input (%s)", self.id, kind)
        if kind in _PAUSING and on_wait:
            _safe(on_wait, True)
        _safe(self.on_input_needed, kind, prompt)

    def _clear_awaiting(self, how: str, on_wait):
        """Caller holds the lock. how: answered | ended | dismissed."""
        kind = self._awaiting[0] if self._awaiting else ""
        self._awaiting = None
        self._answered_at = None
        if kind in _PAUSING and on_wait:
            _safe(on_wait, False)
        _safe(self.on_input_done, how)

    def _check_prompt(self, now: float, checked: dict, on_wait) -> bool:
        """Look at a quiet command's last line. Caller holds the lock.
        Returns True if the user answered a prompt (for the tool result)."""
        answered = False
        if self._awaiting is not None:
            kind = self._awaiting[0]
            if kind == "gcm":
                # Signed in (or closed the window) once the manager has exited.
                if now - self._gcm_checked >= 1.0:
                    self._gcm_checked = now
                    if not self._gcm_running():
                        self._clear_awaiting("answered", on_wait)
                        answered = True
                return answered
            if kind == "input":
                if self._last_output > self._awaiting_since:
                    self._clear_awaiting("dismissed", on_wait)   # it was just output
            elif self._answered_at is not None and self._last_output > self._answered_at:
                self._clear_awaiting("answered", on_wait)
                answered = True
            return answered
        if not self._cap_started:
            return False
        quiet = now - self._last_output
        if (not self.remote and quiet >= _GCM_QUIET
                and now - self._gcm_checked >= _GCM_QUIET):
            self._gcm_checked = now
            if self._gcm_running():
                self._set_awaiting("gcm", _GCM_PROMPT, on_wait)
                return False
        stamp = self._last_output
        need = _INPUT_QUIET if checked.get(stamp) == "specific" else _PROMPT_QUIET
        if quiet < need or checked.get(stamp) == "all":
            return False
        tail = clean_output(self._cap_tail)
        last = tail.rsplit("\n", 1)[-1][-300:] if tail else ""
        kind = classify_prompt(last, quiet)
        checked.clear()
        checked[stamp] = "all" if quiet >= _INPUT_QUIET else "specific"
        if kind:
            self._set_awaiting(kind, last.strip(), on_wait)
        return False

    # ── background commands ───────────────────────────────────────────
    def _take_bg_locked(self) -> Optional[RunResult]:
        """New output of the background command. Caller holds the lock."""
        if self._bg is None:
            return None
        raw = "".join(self._cap_buf)
        start = self._bg["read"] if self._bg["read"] <= len(raw) else 0
        new = raw[start:]
        self._bg["read"] = len(raw)
        done = self._cap_done or not self._alive
        code = self._cap_code if self._cap_done else (None if self._alive else -1)
        if done:
            self._bg = None
            self._cap_active = False
            self._cap_buf, self._cap_tail = [], ""
            self._remote_re = None
        return RunResult(code, clean_output(new), False, running=not done, shell_id=self.id)

    def read_background(self) -> Optional[RunResult]:
        """Output since the last read, and whether it is still running."""
        with self._cond:
            if self._bg is None:
                final, self._bg_final = self._bg_final, None
                return final
            return self._take_bg_locked()

    def kill_background(self) -> Optional[RunResult]:
        """Stop the background command (Ctrl+C, then its processes)."""
        if self._bg is None:
            return self.read_background()
        self.interrupt()
        with self._cond:
            self._cond.wait_for(lambda: self._cap_done or not self._alive, 5)
        return self.read_background()

    # ── AI commands ───────────────────────────────────────────────────
    def wait_ready(self, timeout: float = _READY_TIMEOUT) -> bool:
        with self._cond:
            self._cond.wait_for(lambda: self._ready or not self._alive, timeout)
            return self._ready and self._alive

    def run(self, command: str, idle_timeout: float, hard_cap: float,
            should_stop: Optional[Callable[[], bool]] = None,
            on_wait: Optional[Callable[[bool], None]] = None,
            background: bool = False, startup_wait: float = 8.0,
            ) -> Optional[RunResult]:
        """Run one command as if typed at the prompt.

        Returns a RunResult, or None when the session can't take it right now
        (caller should use another session or a one-off shell). `idle_timeout`
        is the longest allowed silence; output and user typing both reset it.
        `hard_cap` bounds total runtime. Both stop counting while the command
        waits for a password or an answer; `on_wait(True/False)` is called at
        those edges so the caller can pause its own clock. With `background`,
        a command still running after `startup_wait` seconds is left running.
        """
        if not self._run_lock.acquire(timeout=max(5.0, idle_timeout)):
            return None
        tmp = None
        try:
            if not self.wait_ready():
                return None
            remote = self.remote
            # The tab is shared: never type over a command the user started
            # there, or a line they are halfway through typing.
            with self._cond:
                if remote:
                    ok = self._cond.wait_for(lambda: not self._user_dirty or not self._alive, 5)
                else:
                    ok = self._cond.wait_for(
                        lambda: (not self._busy and not self._user_dirty) or not self._alive, 5)
                if not self._alive:
                    return None
                if remote:
                    # The previous command's token is seen a few ms before
                    # the remote shell redraws its prompt, so allow the prompt
                    # a moment to arrive before calling the shell busy.
                    deadline = time.monotonic() + 3.0
                    while True:
                        last = clean_output(self._replay[-2000:]).rsplit("\n", 1)[-1]
                        at_prompt = bool(_SHELL_PROMPT_RE.search(last))
                        if (ok and at_prompt) or not self._alive or time.monotonic() > deadline:
                            break
                        self._cond.wait(0.05)
                    if not ok or not at_prompt:
                        # Never fall back to this machine while connected.
                        return RunResult(-1, "", False, busy=True, shell_id=self.id, remote=remote)
                elif not ok:
                    log.info("[AI-TERM] session %d is in use", self.id)
                    return None
                if self._bg is not None:  # finished earlier; keep it for BashOutput
                    self._bg_final = self._take_bg_locked()

            ssh_dest = None if remote else ssh_destination(command)
            nonce = os.urandom(4).hex() if remote else None
            if remote:
                line = _remote_line(command, nonce,
                                    bool(_setting("ai_sudo_reprompt", True)))
            else:
                line = command.strip()
                # Typing a newline or tab at the prompt would run half a
                # command or trigger completion. Run such commands from a
                # file, dot-sourced so their variables still land in the session.
                if "\n" in line or "\r" in line or "\t" in line or len(line) > 2000:
                    tmp = os.path.join(_SHELL_DIR, f"cmd_{self.id}_{int(time.time() * 1000)}.ps1")
                    with open(tmp, "w", encoding="utf-8-sig") as f:
                        f.write(command)
                    line = ". '" + tmp.replace("'", "''") + "'"

            with self._cond:
                self._cap_active, self._cap_done = True, False
                self._cap_started = bool(remote)   # no C marker over SSH
                self._cap_pre, self._cap_buf, self._cap_len, self._cap_tail = [], [], 0, ""
                self._cap_code = None
                self._remote_re = (re.compile(r"__CX_D" + nonce + r"_(-?\d+)__")
                                   if nonce else None)
                self._remote_dropped = False
                self._last_activity = time.monotonic()
            self.write(line + "\r")

            started = prev = time.monotonic()
            timed_out = connected = left_running = answered = False
            checked: dict = {}
            with self._cond:
                while not self._cap_done and self._alive:
                    now = time.monotonic()
                    if self._check_prompt(now, checked, on_wait):
                        answered = True
                    # Waiting on a person: neither clock runs (a prompt is
                    # never answered by silence). Stop still works.
                    waiting = (self._awaiting is not None
                               and self._awaiting[0] in _PAUSING)
                    if waiting:
                        started += now - prev
                        self._last_activity = now
                    prev = now
                    if ssh_dest and not waiting and self._cap_started \
                            and now - self._last_output >= _SSH_READY_QUIET:
                        last = clean_output(self._cap_tail).rsplit("\n", 1)[-1]
                        if last.strip() and _SHELL_PROMPT_RE.search(last):
                            connected = True
                            break
                    if background and not waiting and now - started >= startup_wait:
                        left_running = True
                        break
                    if (should_stop and should_stop()) or (not background and (
                            now - self._last_activity > idle_timeout
                            or now - started > hard_cap)):
                        timed_out = True
                        break
                    self._cond.wait(0.1)
                if self._awaiting is not None:
                    # git carried on after its sign-in window closed: signed in.
                    gcm_done = self._awaiting[0] == "gcm" and not timed_out
                    if self._answered_at is not None or gcm_done:
                        answered = True
                    self._clear_awaiting("answered" if gcm_done else "ended", on_wait)
            if timed_out:
                self.interrupt()
                with self._cond:
                    self._cond.wait_for(lambda: self._cap_done or not self._alive, 5)

            with self._cond:
                if self._cap_started:
                    raw = "".join(self._cap_buf)
                else:
                    # No C marker (PSReadLine missing): drop the echoed line.
                    raw = "".join(self._cap_pre)
                    raw = raw.split("\n", 1)[1] if "\n" in raw else ""
                code = self._cap_code
                alive = self._alive
                dropped = self._remote_dropped
                rx = self._remote_re
                if not left_running:  # a background command over SSH still ends at its token
                    self._remote_re = None
                if left_running:
                    # Keep capturing: BashOutput reads what comes next.
                    self._bg = {"command": command, "started": started, "read": len(raw)}
                else:
                    self._cap_active = False
                    self._cap_pre, self._cap_buf, self._cap_tail = [], [], ""
                if connected:
                    self.remote = ssh_dest
            if connected:
                log.info("[AI-TERM] session %d: SSH session to %s is ready", self.id, ssh_dest)
                _safe(self.on_remote_changed, ssh_dest)

            out = _strip_remote(raw, rx) if rx is not None else clean_output(raw)
            if len(out) > _OUTPUT_MAX:
                out = "... (earlier output trimmed)\n" + out[-_OUTPUT_MAX:]
            if answered:
                out = (out + "\n\n" if out else "") + ANSWERED_NOTE
            if timed_out:
                return RunResult(-1, out, True, shell_id=self.id, remote=remote)
            if left_running:
                return RunResult(None, out, False, running=True, shell_id=self.id)
            if connected:
                return RunResult(0, out, False, shell_id=self.id, remote=ssh_dest, note=(
                    f"Connected. The Cortex AI terminal is now a shell on {ssh_dest}: your "
                    f"next Bash commands run ON THAT SERVER (use its shell, e.g. bash "
                    f"syntax) until you run `exit`."))
            note = ""
            if dropped and remote:
                note = (f"The SSH session to {remote} ended. The Cortex AI terminal is "
                        f"back on this machine (PowerShell).")
            if code is None:
                code = 0 if alive else -1  # the command ended the shell (exit)
            return RunResult(code, out, False, shell_id=self.id, remote=remote, note=note)
        finally:
            self._run_lock.release()
            if tmp:
                try:
                    os.remove(tmp)
                except OSError:
                    pass


def _safe(fn, *args):
    if fn is None:
        return
    try:
        fn(*args)
    except Exception as e:
        log.warning("[AI-TERM] callback failed: %s", e)


class TerminalSessionManager:
    """Owns the AI's sessions (up to _MAX_AI_SESSIONS) and asks the UI to show them."""

    def __init__(self):
        self._lock = threading.Lock()
        self._sessions: List[TerminalSession] = []
        self._host: Optional[Callable[[TerminalSession], None]] = None
        self._input_needed: Optional[Callable[[TerminalSession, str, str], None]] = None
        self._input_done: Optional[Callable[[TerminalSession, str], None]] = None
        self._remote_changed: Optional[Callable[[TerminalSession, str], None]] = None

    def set_host(self, host: Optional[Callable[[TerminalSession], None]],
                 input_needed: Optional[Callable[[TerminalSession, str, str], None]] = None,
                 input_done: Optional[Callable[[TerminalSession, str], None]] = None,
                 remote_changed: Optional[Callable[[TerminalSession, str], None]] = None):
        """`host(session)` opens a tab for it; `input_needed(session, kind,
        prompt)` / `input_done(session, how)` drive the handover UI;
        `remote_changed(session, host_or_empty)` follows SSH. All are called
        on worker threads, so they must hand off to the GUI thread (e.g. emit
        a signal)."""
        self._host = host
        self._input_needed = input_needed
        self._input_done = input_done
        self._remote_changed = remote_changed

    def enabled(self) -> bool:
        if sys.platform != "win32" or not _WINPTY or self._host is None:
            return False
        try:
            from src.config.settings import get_settings
            return bool(get_settings().get("terminal", "ai_shared_session", default=True))
        except Exception:
            return True

    def sessions(self) -> List[TerminalSession]:
        with self._lock:
            return [s for s in self._sessions if s.is_alive]

    def get(self, shell_id: int) -> Optional[TerminalSession]:
        for s in self.sessions():
            if s.id == shell_id:
                return s
        return None

    def remote_host(self) -> Optional[str]:
        """user@host of the AI's SSH session, if one is connected."""
        for s in self.sessions():
            if s.remote:
                return s.remote
        return None

    @staticmethod
    def _local_allowed() -> bool:
        """Owner decision (2026-09-13): the AI's commands on this PC run hidden
        in a one-off shell, not in a visible Cortex AI tab. Long runs sent
        command after command through the xterm web view, and that was when
        Cortex crashed. The terminal is for server work (SSH) and for what the
        user asks to see (▶ Run). The setting brings the old behaviour back."""
        try:
            from src.config.settings import get_settings
            return bool(get_settings().get("terminal", "ai_local_in_terminal", default=False))
        except Exception:
            return False

    def ai_session(self, cwd: str, env: Optional[dict] = None,
                   local: Optional[bool] = None) -> Optional[TerminalSession]:
        """The session the next command should use: the SSH one if connected,
        else (only when `local` is allowed) an idle one, else a new one
        starting where the busy one is. None means run it elsewhere."""
        if not self.enabled():
            return None
        if local is None:
            local = self._local_allowed()
        root = os.path.normcase(os.path.abspath(cwd)) if cwd else ""
        with self._lock:
            keep = []
            for s in self._sessions:
                if not s.is_alive:
                    continue
                if s.root != root and not s.remote:
                    s.close()  # the project changed
                    continue
                keep.append(s)
            self._sessions = keep
            for s in keep:
                if s.remote:
                    return s
            if not local:
                return None
            for s in keep:
                if s.usable:
                    return s
            if len(keep) >= _MAX_AI_SESSIONS:
                return None
            names = {s.name for s in keep}
            name, n = "Cortex AI", 1
            while name in names:
                n += 1
                name = f"Cortex AI {n}"
            base = keep[0].cwd if keep else cwd
            s = TerminalSession(base, env, name=name)
            s.root = root
            self._wire(s)
            if not s.start():
                return None
            self._sessions.append(s)
        try:
            self._host(s)
        except Exception as e:
            log.warning("[AI-TERM] could not open the Cortex AI tab: %s", e)
        return s

    def _wire(self, s: TerminalSession):
        s.on_input_needed = lambda kind, prompt, s=s: _safe(self._input_needed, s, kind, prompt)
        s.on_input_done = lambda how, s=s: _safe(self._input_done, s, how)
        s.on_remote_changed = lambda host, s=s: _safe(self._remote_changed, s, host)

    def adopt(self, s: TerminalSession):
        """Route AI commands to a user's SSH tab they lent (TerminalSession.adopt).
        A remote session is preferred by ai_session(), so this takes effect at once."""
        self._wire(s)
        with self._lock:
            self._sessions.append(s)

    def run_ai_command(self, command: str, cwd: str, env: Optional[dict],
                       idle_timeout: float, hard_cap: float,
                       should_stop: Optional[Callable[[], bool]] = None,
                       on_wait: Optional[Callable[[bool], None]] = None,
                       background: bool = False,
                       ) -> Optional[RunResult]:
        """Run in a shared session, or None if the caller should fall back.
        `ssh user@host` opens a visible terminal even when local commands run
        hidden: the user types the password there and watches the server work."""
        s = self.ai_session(cwd, env, local=True if ssh_destination(command) else None)
        if s is None:
            return None
        return s.run(command, idle_timeout, hard_cap, should_stop, on_wait,
                     background=background)


_manager: Optional[TerminalSessionManager] = None


def get_terminal_sessions() -> TerminalSessionManager:
    global _manager
    if _manager is None:
        _manager = TerminalSessionManager()
    return _manager
